name: Custom Amplify Pipeline

on:
  push:
    branches:
      - SiteAwareMVP

env:
  AMPLIFY_APP_ID: d8rgmm5whj4ck
  AWS_REGION: us-east-1  # Make sure this is the correct region for your app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: npm ci

      - name: Deploy Backend
        run: |
          export CI=1
          npx ampx pipeline-deploy --branch SiteAwareMVP --app-id $AMPLIFY_APP_ID

      # Add frontend build step if needed
